-- MySQL Script generated by MySQL Workbench
-- Tue Jan 22 16:51:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Author` (
  `Authorid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `AuthorName` VARCHAR(45) NOT NULL,
  `AuthorAddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Authorid`),
  UNIQUE INDEX `Authorid_UNIQUE` (`Authorid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publisher` (
  `Publisher_id` INT NOT NULL AUTO_INCREMENT,
  `Publisher_name` VARCHAR(45) NULL,
  `Publisher_phone` INT NULL,
  `Publisher_URL` VARCHAR(45) NULL,
  `Publisher_Address` VARCHAR(45) NULL,
  PRIMARY KEY (`Publisher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `Book_id_ISBN` INT NOT NULL AUTO_INCREMENT,
  `Book_price` DECIMAL NOT NULL,
  `Publish_year` YEAR NULL,
  `Title` VARCHAR(45) NULL,
  `Author_Authorid` INT UNSIGNED NOT NULL,
  `Publisher_Publisher_id` INT NOT NULL,
  PRIMARY KEY (`Book_id_ISBN`, `Author_Authorid`, `Publisher_Publisher_id`),
  INDEX `fk_Book_Author_idx` (`Author_Authorid` ASC) VISIBLE,
  INDEX `fk_Book_Publisher1_idx` (`Publisher_Publisher_id` ASC) VISIBLE,
  CONSTRAINT `fk_Book_Author`
    FOREIGN KEY (`Author_Authorid`)
    REFERENCES `mydb`.`Author` (`Authorid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Book_Publisher1`
    FOREIGN KEY (`Publisher_Publisher_id`)
    REFERENCES `mydb`.`Publisher` (`Publisher_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `Customer_Email` VARCHAR(45) NOT NULL,
  `Customer_Name` VARCHAR(45) NULL,
  `Customer_phone` INT NULL,
  `Customer_Address` VARCHAR(45) NULL,
  PRIMARY KEY (`Customer_Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shopping_Basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shopping_Basket` (
  `Shopping_Basket_id` INT NOT NULL,
  `Customer_Customer_Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Shopping_Basket_id`, `Customer_Customer_Email`),
  INDEX `fk_Shopping_Basket_Customer1_idx` (`Customer_Customer_Email` ASC) VISIBLE,
  CONSTRAINT `fk_Shopping_Basket_Customer1`
    FOREIGN KEY (`Customer_Customer_Email`)
    REFERENCES `mydb`.`Customer` (`Customer_Email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouse` (
  `Warehouse_id` INT NOT NULL AUTO_INCREMENT,
  `Warehouse_phone` VARCHAR(45) NULL,
  `Warehouse_address` VARCHAR(45) NULL,
  PRIMARY KEY (`Warehouse_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Warehouses_have_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouses_have_books` (
  `Warehouse_Warehouse_id` INT NOT NULL,
  `Book_Book_id_ISBN` INT NOT NULL,
  `Book_Author_Authorid` INT UNSIGNED NOT NULL,
  `Book_Publisher_Publisher_id` INT NOT NULL,
  PRIMARY KEY (`Warehouse_Warehouse_id`, `Book_Book_id_ISBN`, `Book_Author_Authorid`, `Book_Publisher_Publisher_id`),
  INDEX `fk_Warehouses_have_books_Warehouse1_idx` (`Warehouse_Warehouse_id` ASC) VISIBLE,
  INDEX `fk_Warehouses_have_books_Book1_idx` (`Book_Book_id_ISBN` ASC, `Book_Author_Authorid` ASC, `Book_Publisher_Publisher_id` ASC) VISIBLE,
  CONSTRAINT `fk_Warehouses_have_books_Warehouse1`
    FOREIGN KEY (`Warehouse_Warehouse_id`)
    REFERENCES `mydb`.`Warehouse` (`Warehouse_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Warehouses_have_books_Book1`
    FOREIGN KEY (`Book_Book_id_ISBN` , `Book_Author_Authorid` , `Book_Publisher_Publisher_id`)
    REFERENCES `mydb`.`Book` (`Book_id_ISBN` , `Author_Authorid` , `Publisher_Publisher_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
